[package]
name = "advent_of_code_2023"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }
itertools = "0.12.0"
rayon = "1.7.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0"
